apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: ingress
    chart: nginx-ingress-controller
spec:
  project: default
  source:
    repoURL: https://github.com/leo-asdf/petclinic-argocd
    targetRevision: main
    path: nginx-ingress-controller
    helm:
      releaseName: nginx-ingress-controller
      valueFiles:
        - values.yaml
  destination:
    name: minikube
    namespace: default
  syncPolicy:
    automated:
      prune: true
