apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: petclinic
    chart: petclinic-app
spec:
  project: default
  source:
    repoURL: https://github.com/leo-asdf/petclinic-argocd
    targetRevision: main
    path: petclinic/petclinic-app
    helm:
      releaseName: petclinic-app
      valueFiles:
        - values.yaml
  destination:
    name: minikube
    namespace: default
  syncPolicy:
    automated:
      prune: true
