
{{ if .Values.configMapDataCreate }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.applicationName }}-data-config
  namespace: {{ .Values.namespace }}
data:
  {{- with .Values.configMapData }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- range $name, $config := .Values.configMapDataYaml }}
    {{- $name | nindent 2 }}: |
      {{- toYaml $config | nindent 4 }}
  {{- end }}
{{ end }}
{{ if .Values.configMapEnvCreate }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.applicationName }}-env-config
data:
  {{- with .Values.configMapEnvData }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{ end }}