apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: petclinic
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: syl1709/petclinic:3.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.containerPort }}
          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.healthPort }}
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.healthPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.healthPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 2
          {{- if .Values.env }}
          env:
          {{- include "env" .Values | nindent 10}}
          {{- end }}
          {{- if .Values.envFrom }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12}}
          {{- end }}
          volumeMounts:
            - name: app-logs
              mountPath: /opt/devops/logs
            - name: logback-spring-config
              mountPath: /opt/devops/config/logback-spring.xml
              subPath: logback-spring.xml
            - name: application-properties-config
              mountPath: /opt/devops/config/application.properties
              subPath: application.properties
      volumes:
        - name: app-logs
          hostPath:
            path: /logs
            type: Directory
        - name: logback-spring-config
          configMap:
            name: petclinic-logback-spring-config
            items:
              - key: logback-spring.xml
                path: logback-spring.xml
        - name: application-properties-config
          configMap:
            name: petclinic-application-propeties-config
            items:
              - key: application.properties
                path: application.properties
      terminationGracePeriodSeconds: 30
