apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: petclinic
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.periodSeconds }}
            failureThreshold: {{ .Values.probe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.periodSeconds }}
            failureThreshold: {{ .Values.probe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.periodSeconds }}
            failureThreshold: {{ .Values.probe.failureThreshold }}
          envFrom:
            - configMapRef:
                name: petclinic-env-config
          volumeMounts:
            - name: app-logs
              mountPath: {{ .Values.logsPath }}
            - name: logback-spring-config
              mountPath: /opt/devops/config/logback-spring.xml
              subPath: {{ .Values.config.logbackSpring.key }}
            - name: application-properties-config
              mountPath: /opt/devops/config/application.properties
              subPath: {{ .Values.config.applicationProperties.key }}
      volumes:
        {{- range $k, $v := .Values.volumes}}
        - name {{ $k }}
          {{- toYaml $v | nindent 10 }}
        {{- end}}
      terminationGracePeriodSeconds: 30
