apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: petclinic
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: petclinic
          image: syl1709/petclinic:3.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.containerPort }}
          {{- if .Values.startupProbe }}
          startupProbe:
            {{- with .Values.startupProbe }}
            {{ toYaml . | nindent 12}}
            {{- end }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- with .Values.livenessProbe }}
            {{ toYaml . | nindent 12}}
            {{- end }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- with .Values.readinessProbe }}
            {{ toYaml . | nindent 12}}
            {{- end }}
          {{- end }}
          {{- if .Values.env }}
          env:
            {{- include "env" .Values | nindent 12}}
          {{- end }}
          {{- if .Values.envFrom }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12}}
          {{- end }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
            {{- include "volume_mount" .Values | nindent 12}}
          {{- end }}
      {{- if .Values.volumes }}
      volumes:
        {{- include "volume" .Values | nindent 8}}
      {{- end }}
